---
title: "Get data"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r yourvariables}

# what are you searching for
query <- '"artificial intelligence"'

query <- '"technology in relation to its enterprise that is likely to have a significant effect on the employees" AND (automation OR automated OR "artificial intelligence")'

```


```{r setup}

pacman::p_load(curl, 
               magrittr, 
               dplyr, 
               purrr, 
               rvest, 
               glue, 
               httr, 
               jsonlite, 
               readr, 
               httr)

source(here::here("R/params.R"))

source(here::here("R/functions/get_query_count.R"))
source(here::here("R/functions/sanitize_flename.R"))
source(here::here("R/functions/get_page_data.R"))
source(here::here("R/functions/download_pdf_viewer.R"))

source(here::here("R/params_constructed.R"))


```


```{r getdata}

# Check for existing files matching the pattern
matching_files <- list.files(here::here("data"), pattern = file_pattern, full.names = TRUE)


if (length(matching_files) > 0) {
  # If multiple matching files are found, use the most recently dated
  latest_file <- matching_files[which.max(file.info(matching_files)$mtime)]
  
  # Ask if the user wants to re-query
  message("Matching file found: ", latest_file)
  user_response <- readline(prompt = "Do you want to re-query the data? (yes/no): ")
  
  if (tolower(user_response) == "no") {
    # Load the existing file
    message("Loading the existing file...")
    documents <- readRDS(latest_file)
  }} else {
    # Run the block and save the output with today's date
    message("querying the data...")
    all_data <- map(1:pages, ~get_page_data(base_query, .x))
    
    # Extract and combine the results from each page
    documents <- all_data %>%
        # Filter out NULL results (in case some pages failed to load)
        compact() %>%
        # Extract the `documentResult$results` from each page and convert to tibble
        map_dfr(~ .x$documentResult$results %>% as_tibble())
    
    output_file <- file.path(data_dir, paste0(Sys.Date(), "-", gsub(" ", "-", sanitized_filename), ".rds"))
    saveRDS(documents, output_file)
    message("Data saved to: ", output_file)
}



```

```{r getpdfs}

# Ask if the user wants pdf or txt
user_response <- readline(prompt = "Do you want to get the pdfs or write the txt to files? (pdf/txt): ")
  
if (tolower(user_response) == "pdf") {
    if(dir.exists(paste0(data_dir, "/pdf")) == FALSE) {
      dir.create(paste0(data_dir, "/pdf"))
    }
  # Use walk2 to iterate over metadata_storage_path and PublicationID
  walk2(documents$document.metadata_storage_path,
        documents$document.PublicationID,
        ~ download_pdf_viewer(
            encoded_path = .x,
            publication_id = .y)
        )

} else {
    if (tolower(user_response) == "txt") {
    if(dir.exists(paste0(data_dir, "/txt")) == FALSE) {
      dir.create(paste0(data_dir, "/txt"))
    }
    
    walk2(documents$document.text,
          documents$document.PublicationID,
          ~ readr::write_lines(.x,
                               file = paste0(data_dir,"/txt/", .y, ".txt")
          ))
    }
}


```

